### ISSUE TITLE
Add get_structures() in SampleContainer

### ISSUE THREAD

**Issue by jic198** [CederGroupHub/smol#296]
**Is your feature request related to a problem? Please describe.**
This feature is about getting a pymatgen `Structure` object from an occupancy sampled by MC. The only way I’ve found so far is this: `ensemble.processor.structure_from_occupancy(sampler.samples.get_occupancies()[-1])`, which is OK, even though I think it could be better. But I am just thinking about a scenario when I read the json file saved by `SampleContainer` after MC, I have to create an `Ensemble` object to get the structure. To create this `Ensemble` object, I need a `ClusterExpansion` object and a supercell matrix, and I don't know if the supercell matrix has been saved. So I will need to have a lot of info before I can get the structure from an occupancy.

**Describe the solution you'd like**
I am still thinking about it.

**Describe alternatives you've considered**
I am still thinking about it.

**Comment by lbluque** [comment]
Thanks @jic198 !

This is a very good point. It would be much more straightforward to have a direct way to recover a `Structure` object directly from a `SampleContainer`.

Although as you mention it is a bit 'convoluted' since the information to be able to recover the correct structure is all saved in the `Processor` class that was used for MC. The first idea I can think of to solve this might be to simply save the processor as an attribute in the `SampleContainer`.

**Comment by lbluque** [comment]
I am thinking for this we can just keep the `Ensemble` as an attribute of the `SampleContainer` since both are `MSONable` and then it can be saved for future use.

**Comment by lbluque** [comment]
Hi @jic198 :wave: Have a look at #326 which now adds a method `get_sampled_structures` to a `SampleContainer`.
