### ISSUE TITLE
Numpy pinned to 1.23.5? 

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/smol#339]
**Is your feature request related to a problem? Please describe.**
Numpy dependency for smol has not been upgraded for a while. @lbluque could you please explain what is happening with newer versions of numpy?

**Comment by lbluque** [comment]
The issue is with `emmet` a dependency of pymatgen:
https://github.com/materialsproject/emmet/issues/624

It seems its been fixed so I will update numpy now.

By the way the actually dependency versions are the ones listed in setup.cfg not the ones listed in requirements.txt (those are used for CI purposes only)
